services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=${DEBUG:-0}
      - SERVICES=secretsmanager,kms,cloudformation,ec2
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test123supersafe
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  setup:
    build:
      context: .
      dockerfile: Dockerfile_setup_aws
    image: my-aws-cli
    platform: linux/amd64
    container_name: setup-localstack
    depends_on:
      - localstack
    volumes:
      - .:/app
    working_dir: /app

  oauth2-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oauth2-app
    ports:
      - "3000:3000"
    depends_on:
      setup:
        condition: service_completed_successfully
    volumes:
      - .:/usr/src/app
