AWSTemplateFormatVersion: "2010-09-09"
Description: OAuth2 client credentials secret

Resources:
  OAuthCredentialsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: oauth/credentials
      Description: OAuth2 client credentials for testing
      SecretString: |
        {
          "client1": { "secret": "dummysecret1", "scopes": ["default"] },
          "client2": { "secret": "dummysecret2", "scopes": [] }
        }

Outputs:
  SecretArn:
    Description: ARN of the OAuth2 credentials secret
    Value: !Ref OAuthCredentialsSecret
